version: '3.1'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - 3306:3306

  pma:
    image: 'bitnami/phpmyadmin:latest'
    labels:
      kompose.service.type: nodeport
    depends_on:
      - mariadb
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: Host:$HOSTNAME
        traefik.docker.network: traefik-net

networks:
  traefik-net:
    external:
      name: traefik-net

volumes:
  mariadb_data:
